### ISSUE TITLE
KLUSTERLET_KIND_KUBECONFIG removal from documentation and Makefile

### ISSUE THREAD

**Issue by hatfieldbrian** [open-cluster-management-io/registration-operator#107]
`KLUSTERLET_KIND_KUBECONFIG` variable use was removed from `Makefile` with commit `b49b80b` in branch `main`.  Please remove it from corresponding documentation https://open-cluster-management.io/getting-started/register-cluster/#install-from-source and its definition/assignment from the `Makefile` https://github.com/open-cluster-management/registration-operator/blob/fb28c38365b93e0c7b2bc93b7706da266cfec587/Makefile#L40

**Comment by qiujian16** [comment]
fixed
