### ISSUE TITLE
Pull "busybox" failed

### ISSUE THREAD

**Issue by xuezhaojun** [open-cluster-management-io/registration-operator#113]
We followed steps in https://open-cluster-management.io/getting-started/register-cluster/

But in the end we see:
```
NAME    READY   STATUS             RESTARTS   AGE
hello   0/1     ImagePullBackOff   0          81s
```
we find logs shows:
```
Failed to pull image "busybox": rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/library/busybox:latest": failed to copy: httpReaderSeeker: failed open: unexpected status code
```

We suggest :
1. change image used in `manifest-work.yaml` to a image exist in `quay.io`
2. use `deployment` instead of `pod` in `manifest-work.yaml`

**Comment by qiujian16** [comment]
I think it is fixed
