### ISSUE TITLE
Failed to use ManifestWork apply a k8s deployment.

### ISSUE THREAD

**Issue by hahchenchen** [open-cluster-management-io/registration-operator#126]
when i use ManifestWork to apply a k8s deployment, the ManifestWork output an  error:

resourceStatus:
    manifests:
    - conditions:
      - lastTransitionTime: "2021-06-07T06:20:01Z"
        message: 'Failed to apply manifest: the server does not allow this method
          on the requested resource'
        reason: AppliedManifestFailed
        status: "False"
        type: Applied
      - lastTransitionTime: "2021-06-07T06:20:01Z"
        message: Resource is not available
        reason: ResourceNotAvailable
        status: "False"
        type: Available
      resourceMeta:
        group: apps
        kind: Deployment
        name: nginx-deployment
        namespace: ""
        ordinal: 0
        resource: deployments
        version: v1

Are there any restrictions on creating a deployment? such as rbac?

the manifestwork.yaml is:
apiVersion: work.open-cluster-management.io/v1
kind: ManifestWork
metadata:
  name: mw-02
  namespace: cluster1
spec:
  workload:
    manifests:
    - apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nginx-deployment
        labels:
          app: nginx
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: nginx
        template:
          metadata:
            labels:
              app: nginx
          spec:
            containers:
            - name: nginx
              image: nginx:latest

**Comment by qiujian16** [comment]
I think you would need to add the namespace in the deployment manifest. The work agent does not take `default` as the default ns.

**Comment by qiujian16** [comment]
this is a configuration issue, not a bug
