### ISSUE TITLE
Allow klusterlet to run outside of managed cluster

### ISSUE THREAD

**Issue by qiujian16** [open-cluster-management-io/registration-operator#158]
We should allow klusterlet (and all addons) to run outside of managed cluster.

This is useful when we want to:
1. run klusterlet on the hub cluster.
2. run klusterlet on a different cluster due to firewall setup.

/assign @zhujian7

**Comment by zhujian7** [comment]
As of now, klusterlet can be run outside the managed cluster, but addons still can not.
I think the addon part should not be in release v0.6

**Comment by zhujian7** [comment]
Proposal: https://github.com/open-cluster-management-io/enhancements/pull/36

**Comment by qiujian16** [comment]
I think this has been finished

/close
