### ISSUE TITLE
work-agent restart, not found hub-kubeconfig

### ISSUE THREAD

**Issue by wangzd1** [open-cluster-management-io/registration-operator#182]
I deploy-spoke the operator in a managed cluster, but the work-agent always backoff because of not found "/spoke/hub-kubeconfig/kubeconfig".I can't find which step to generate the "hub-kubeconfig-secret" secret.Is it necessary to create the agent ns and generate the secret in advance.

**Comment by qiujian16** [comment]
the secret will be auto generated when you run `clusteradm accept --cluster xxx` on hub.

**Comment by wangzd1** [comment]
I deploy-spoke from source,not by clusteradm accept.
Is it will generate secret aoto?

**Comment by qiujian16** [comment]
then you would need to approve csr and set managedcluster.spec.hubAcceptClient true. see here https://github.com/open-cluster-management-io/registration-operator#what-is-next

**Comment by wangzd1** [comment]
ok，thanks
